version: '3.4'
services:
  devbox:
    build:
      context: .
      dockerfile: ./docker/devbox.dockerfile
    image: lumen/devbox
    command: /bin/bash
    volumes:
      - ./:/app

  test:
    environment:
      FLASK_CONFIG: 'lumen.config.LocalConfig'
    build:
      context: .
      dockerfile: ./docker/devbox.dockerfile
    image: lumen/devbox
    entrypoint: /bin/bash ./docker/run_tests.sh
    volumes:
      - ./:/app

  service:
    environment:
      FLASK_CONFIG: "lumen.config.LocalConfig"
      FLASK_APP: "lumen.app:create_app()"
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: local
      POSTGRES_DATABASE_URI: "postgresql://dbuser:dbpassword@localdb:5432/lumendb"
      FLASK_DEBUG: "True"
    build:
      context: .
      dockerfile: ./docker/service.dockerfile
    image: lumen/service
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - lumen
  
  db:
    image: postgres:11.3
    restart: always
    container_name: localdb
    environment:
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_USER: dbuser
      POSTGRES_DB: lumendb
    ports:
      - '5432:5432'
    networks:
      - lumen
    volumes:
      - ./db-data:/app/postgresql/data

networks:
  lumen:
