# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt -r requirements-test.txt
      - run:
          name: black
          command: |
            . venv/bin/activate
            black --check -l 120 lumen
            black --check -l 120 tests
      - run:
          name: flake8
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: mypy
          command: |
            . venv/bin/activate
            mypy lumen --ignore-missing-imports
      - run:
          name: pytest
          command: |
            . venv/bin/activate
            pytest tests
